apiVersion: v1
kind: ConfigMap
metadata:
  name: quotes-config
data:
  QUOTES: "To be or not to be|All that glitters is not gold|The only way to do great work is to love what you do"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-quote-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-quote-api
  template:
    metadata:
      labels:
        app: random-quote-api
    spec:
      containers:
      - name: random-quote-api
        image: leeroycodes/random-quote-api:v1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: quotes-config
---
apiVersion: v1
kind: Service
metadata:
  name: random-quote-api-service
spec:
  type: LoadBalancer
  selector:
    app: random-quote-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000